### ISSUE TITLE
nginx can't bind to 80 and 443, as they are already in use

### ISSUE THREAD

**Issue by mariusGundersen** [MarvAmBass/docker-piwik#5] opened 2015-01-13 19:55 UTC
This is the output I get from starting this container. As you can see at the bottom the nginx is unable to bind to port 80. The result is that the piwik instance is not running correctly.

```
Welcome to the marvambass/nginx-ssl-secure container

IMPORTANT:
  IF you use SSL inside your personal NGINX-config,
  you should add the Strict-Transport-Security header like:

    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";

  to your config.
  After this you should gain a A+ Grade on the Qualys SSL Test

>> copy /etc/nginx/external/*.conf files to /etc/nginx/conf.d/
>> piwik is configured to listen behind a reverse proxy now
>> HSTS Headers disabled
>> set MYSQL Host: mysql
>> set MYSQL Port: 3306
>> set MYSQL User: <hidden>
>> set MYSQL Password: <hidden>
>> set MYSQL DB Name: piwik
>> set MYSQL Prefix: piwik_
>> making piwik available beneath: /
>> adding softlink from /piwik to /

>> #####################
>> init piwik
>> #####################

>> update CorePlugins
Add the following JS-Code to your Site -> don't forget to change the URLs ;)

<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//!!!YOUR-URL!!!/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 1]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<noscript><p><img src="//!!!YOUR-URL!!!/piwik.php?idsite=1" style="border:0;" alt="" /></p></noscript>
<!-- End Piwik Code -->
>> exec docker CMD
nginx
2015/01/13 19:45:09 [emerg] 53#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/01/13 19:45:09 [emerg] 53#0: bind() to 0.0.0.0:443 failed (98: Address already in use)
2015/01/13 19:45:09 [notice] 53#0: try again to bind() after 500ms
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
nginx: [emerg] bind() to 0.0.0.0:443 failed (98: Address already in use)
2015/01/13 19:45:09 [notice] 53#0: using the "epoll" event method
2015/01/13 19:45:09 [notice] 53#0: nginx/1.7.9
2015/01/13 19:45:09 [notice] 53#0: built by gcc 4.7.2 (Debian 4.7.2-5)
2015/01/13 19:45:09 [notice] 53#0: OS: Linux 3.18.1-x86_64-linode50
2015/01/13 19:45:09 [notice] 53#0: getrlimit(RLIMIT_NOFILE): 524288:1048576
2015/01/13 19:45:09 [notice] 53#0: start worker processes
2015/01/13 19:45:09 [notice] 53#0: start worker process 54
```

Any idea what could cause this?

**Comment by MarvAmBass** [comment] 2015-01-13 20:51
Hi Marius,

can you tell me more about your environment? I just checked the lastest image on my Notebook. It works like a charm.

My Environment:
Ubuntu 14.04

Docker: docker version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8


__docker run -ti marvambass/piwik__

    Welcome to the marvambass/nginx-ssl-secure container

    IMPORTANT:
      IF you use SSL inside your personal NGINX-config,
      you should add the Strict-Transport-Security header like:

        add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";

      to your config.
      After this you should gain a A+ Grade on the Qualys SSL Test

    >> seems like the first start of nginx
    >> doing some preparations...

    >> generating /etc/nginx/external/dh.pem with size: 1024
    Generating DH parameters, 1024 bit long safe prime, generator 2
    This is going to take a long time
    ....................................................................................+....+.............+...+......................+..........................................................................................+.......................................................................................+...............................+.................................+.......................................+............+.........+...................................................................................................++*++*++*
    >> generating self signed cert
    Generating a 4086 bit RSA private key
    .........................................................................++
    ................................++
    writing new private key to '/etc/nginx/external/key.pem'
    -----
    >> copy /etc/nginx/external/*.conf files to /etc/nginx/conf.d/
    >> piwik is configured to listen behind a reverse proxy now
    >> HSTS Headers disabled
    >> set MYSQL Host: mysql
    >> set MYSQL Port: 3306
    >> set MYSQL User: <hidden>
    >> set MYSQL Password: <hidden>
    >> set MYSQL DB Name: piwik
    >> set MYSQL Prefix: piwik_
    >> making piwik available beneath: /piwik/
    >> adding softlink from /piwik to /piwik/
    >> piwik started, initial setup needs to be done in browser!
    >> be fast! - anyone with access to your server can configure it!
    >> exec docker CMD
    nginx
    2015/01/13 20:47:32 [notice] 44#0: using the "epoll" event method
    2015/01/13 20:47:32 [notice] 44#0: nginx/1.7.9
    2015/01/13 20:47:32 [notice] 44#0: built by gcc 4.7.2 (Debian 4.7.2-5) 
    2015/01/13 20:47:32 [notice] 44#0: OS: Linux 3.13.0-43-generic
    2015/01/13 20:47:32 [notice] 44#0: getrlimit(RLIMIT_NOFILE): 524288:1048576
    2015/01/13 20:47:32 [notice] 44#0: start worker processes
    2015/01/13 20:47:32 [notice] 44#0: start worker process 45
    ^C2015/01/13 20:47:42 [notice] 44#0: signal 2 (SIGINT) received, exiting
    2015/01/13 20:47:42 [notice] 45#0: signal 2 (SIGINT) received, exiting
    2015/01/13 20:47:42 [info] 45#0: epoll_wait() failed (4: Interrupted system call)
    2015/01/13 20:47:42 [notice] 45#0: exiting
    2015/01/13 20:47:42 [notice] 45#0: exit
    2015/01/13 20:47:42 [notice] 44#0: signal 17 (SIGCHLD) received
    2015/01/13 20:47:42 [notice] 44#0: worker process 45 exited with code 0
    2015/01/13 20:47:42 [notice] 44#0: exit

**Comment by MarvAmBass** [comment] 2015-01-13 21:00
tried a bit more, but I can't reproduce the error

**Comment by mariusGundersen** [comment] 2015-01-14 08:54
I made a new Dockerfile FROM yours, with some of the ENV variables I wanted. It might have been caused by a combination of the variables present, since I got it to work later. Here is a docker file that I used to recreate the problem:

```
FROM marvambass/piwik
MAINTAINER marius gundersen

ENV PIWIK_RELATIVE_URL_ROOT     /

ENV PIWIK_ADMIN                 admin
ENV PIWIK_ADMIN_MAIL            admin@mysite.com
ENV PIWIK_ADMIN_PASSWORD        superSecret

ENV PIWIK_MYSQL_USER            piwik
ENV PIWIK_MYSQL_PASSWORD        password
ENV SITE_NAME                   mysite.com
```

**Comment by MarvAmBass** [comment] 2015-01-14 09:32
Hi Marius,

even this small Dockerfile works on my Notebook with no Problems.

But if you've figured it out, I'll close this issue.

Can you just comment, what you did to fix it? The only thing I can think of would be some special character inside a password variable or something like that

**Comment by mariusGundersen** [comment] 2015-01-14 09:37
The docker file I went with removed the PIWIK_ADMIN_PASSWORD and added the SITE_URL ENV variables. It might be that the setup process fails, and then the nginx isn't killed correctly before it is restarted again.

**Comment by MarvAmBass** [comment] 2015-01-14 09:44
normally you shouldn't be able to remove the PIWIK_ADMIN_PASSWORD variable. If it doesn't exists or is not set, the setup process gernerates one. The SITE_URL shouldn't be a Problem.

I'll close this now as invalid.

**Closed by MarvAmBass** 2015-01-14 09:44 UTC
Labels: invalid
